language: generic

install:
  - ./download.sh
  - ./deploy.sh

script:
  - ./wait.sh
  - gradle test

notifications:
  slack:
    rooms:
      secure: sDU+APG+16FoNKnJbHorYaDrx/1SOG3RCa18KTv/W2OFRDUhhrsHY/Q378Q7NfRG9qAiREr21Avxc+N3j/6WCBGfW739lxm9G3w3ihPa8V3SB6YgJkFCCrh9aZHfht7qzjCelNgIe2mGw+cHbtukSyG+l+Ah5GNUJro3mYT1ZgEKtuL9Yu9B7FMeGnXuDOxfvobodbZVPxYxbClfmVax7tmA5PtQfj1WBb9BEG1yEYc2InFlAp7jsjLxESnvHh02FZWXUVpN6fyUosvsDJe7kvs8a/VcSzeiKAN7YMEF7bLCEEZjJdgr4Ick7SloPeLxmo6nkLRk8sSgFO2bn8cwExHhU8Byav1qNOBuFvnyh4Z80B2JyqhoDCzxI/WoKFImAL0gEVl9K+smrZ+1bQKoUN10YxbPbPwcc2JUMGIgXcqvkhO1JwW/tVpUhJ8IBCWgdYC/FXkI09ZyaL5Ufd5q+ZXEydpJNaZKfYIIlkwzon2jXz/9KT97PWD+zxFakPknBOIG/uWwB6WJkx1DvG6p4upH1qxELGPQbR2Txgq1VAC4IZQJOfp4q3FnBxigKPSsDxvfzRtKw4a8pws8RM2EDaFyTKUD8uHgpUsEq4p/p74+hOc05fpkZ7v6Qn5rI+i7cnhPZat3m+ebfUtsrlAUjAW3XOK2f8lCKu4tW8n5Y+E=
    on_success: always
    on_failure: always
