language: generic

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox libnss3-tools --fix-missing
  - curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname -s`-`uname -m` > docker-machine
  - chmod +x ./docker-machine
  - ./docker-machine create --driver virtualbox tryggve
  - ./docker-machine create --driver virtualbox tsd
  - brew install mkcert
  - mkcert -install
  - curl -L https://github.com/uio-bmi/crypt4gh/releases/download/v2.2.0/crypt4gh.jar

script:
  - echo "test"
