language: java

jdk:
  - oraclejdk13

cache:
  directories:
    - $HOME/.m2

before_install: source install.sh

install:
  - source bootstrap.sh
  - source deploy.sh

script:
  - sleep 300
  - mvn test

after_failure:
  - docker service logs LEGA_proxy
  - docker service logs LEGA_ingest
  - docker service logs LEGA_verify
  - docker service logs LEGA_finalize
  - docker service logs LEGA_mapper
  - docker service logs LEGA_interceptor
  - docker service logs LEGA_doa
