language: java

jdk:
  - oraclejdk13

cache:
  directories:
    - $HOME/.m2

before_install: source install.sh

install:
  - source bootstrap.sh
  - source deploy.sh

script:
  - sleep 120
  - mvn test

after_failure: docker service logs
