language: generic

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

install:
  - apt-get install -q libnss3-tools --fix-missing
  - brew install mkcert
  - mkcert -install
  - curl -L https://github.com/uio-bmi/crypt4gh/releases/download/v2.2.0/crypt4gh.jar

script:
  - echo "test"
