language: java

jdk:
  - oraclejdk13

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_install: source install.sh

install:
  - source bootstrap.sh
  - source deploy.sh

script:
  - sleep 60
  - mvn test
