language: generic

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

install:
  - curl -L https://github.com/FiloSottile/mkcert/releases/download/v1.4.1/mkcert-v1.4.1-linux-amd64 > mkcert
  - chmod +x ./mkcert
  - ./mkcert -install
  - curl -L https://github.com/uio-bmi/crypt4gh/releases/download/v2.2.0/crypt4gh.jar

script:
  - echo "test"
