version: '3.3'

services:

  db:
    image: nbisweden/ega-db:m7-v2
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - DB_LEGA_IN_PASSWORD
      - DB_LEGA_OUT_PASSWORD
      - PGDATA=/ega/data
      - PG_SERVER_CERT=/etc/ega/pg.cert
      - PG_SERVER_KEY=/etc/ega/pg.key
      - PG_CA=/etc/ega/CA.cert
      - PG_VERIFY_PEER=1
    configs:
      - source: server.pem
        target: /etc/ega/pg.cert
        uid: '70'
        gid: '70'
        mode: 0600
      - source: server-key.key
        target: /etc/ega/pg.key
        uid: '70'
        gid: '70'
        mode: 0600
      - source: rootCA.pem
        target: /etc/ega/CA.cert
        uid: '70'
        gid: '70'
        mode: 0600
    volumes:
      - db:/ega/data

  vault-s3:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    configs:
      - source: server.pem
        target: /root/.minio/certs/public.crt
      - source: server-key.pem
        target: /root/.minio/certs/private.key
      - source: rootCA.pem
        target: /root/.minio/CAs/LocalEGA.crt
    volumes:
      - vault_s3:/data
    command: server /data

  ingest:
    image: egarchive/lega-base:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    configs:
      - source: conf.ini
        target: /etc/ega/conf.ini
      - source: client.pem
        target: /etc/ega/ssl.cert
      - source: client-key.pem
        target: /etc/ega/ssl.key
        uid: '1000'
        gid: '1000'
        mode: 0600
      - source: rootCA.pem
        target: /etc/ega/CA.cert
    volumes:
      - "$INBOX_LOCATION/$INBOX_BUCKET:/ega/inbox"
    user: lega
    entrypoint: ["ega-ingest"]

  verify:
    image: egarchive/lega-base:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - LEGA_PASSWORD
      - S3_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - S3_SECRET_KEY=${MINIO_SECRET_KEY}
    configs:
      - source: conf.ini
        target: /etc/ega/conf.ini
      - source: client.pem
        target: /etc/ega/ssl.cert
      - source: client-key.pem
        target: /etc/ega/ssl.key
        uid: '1000'
        gid: '1000'
        mode: 0600
      - source: rootCA.pem
        target: /etc/ega/CA.cert
    user: lega
    entrypoint: ["ega-verify"]

  finalize:
    image: egarchive/lega-base:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    configs:
      - source: conf.ini
        target: /etc/ega/conf.ini
      - source: client.pem
        target: /etc/ega/ssl.cert
      - source: client-key.pem
        target: /etc/ega/ssl.key
        uid: '1000'
        gid: '1000'
        mode: 0600
      - source: rootCA.pem
        target: /etc/ega/CA.cert
    user: lega
    entrypoint: ["ega-finalize"]

volumes:
  vault_s3:
  db:

configs:
  rootCA.pem:
    external: true
  server.pem:
    external: true
  server-key.pem:
    external: true
  client.pem:
    external: true
  client-key.pem:
    external: true
  conf.ini:
    external: true
  ega.sec:
    external: true
  ega.sec.pass:
    external: true
  ega.pub:
    external: true
